### PR TITLE
fix(node-modules-polyfill): replace `rollup-plugin-node-polyfills` with `rollup-plugin-polyfill-node`

### LINKED ISSUE #18: [node-modules-polyfill] Replace unmaintained `rollup-plugin-node-polyfills` dependency
Same reasoning as in https://github.com/ionic-team/rollup-plugin-node-polyfills/pull/32.

Since that repo is never touched in the last 3 years, it's probably a good idea to either look at the community forks (see https://github.com/ionic-team/rollup-plugin-node-polyfills/issues/28) _or_ create our own fork.
I would prefer to use @FredKSchott [fork](https://github.com/FredKSchott/rollup-plugin-polyfill-node) as he's the creator of `snowpack` & that's the one used by the `snowpack` library too, so it probably has the most up to date version of the `rollup-plugin-node-polyfills` lib.

Edit: @FredKSchott's fork is also recommended by the @rollup team: https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Closes #18

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@remorses This one's good to be merged now I think

**Comment by imranbarbhuiya** [comment]
using this pr (after building locally), I get this error 
image

**Comment by MichaelDeBoey** [comment]
@remorses Is there anything I still need to do to get this one merged?

**Comment by remorses** [comment]
I have to test everything works locally first, I have been busy

**Comment by MichaelDeBoey** [comment]
@remorses Let me know if I can help you out in some way

**Comment by matikucharski** [comment]
@remorses When it can be merged?

**Comment by MichaelDeBoey** [comment]
@remorses Any update on this one?
We would love to have this merged for the Remix cli

File: node-modules-polyfill/src/index.ts [hunk 1]
```diff
@@ -52,7 +52,7 @@ export function NodeModulesPolyfillPlugin(
 
                     const resolved = polyfilledBuiltins.get(
```
Comment (connorjclark) [inline node-modules-polyfill/src/index.ts:53]: I tried this patch but it didn't work for me because `polyfilledBuiltins` values is the actual polyfill content, not the path, as the rest of this plugin expects.

This changed for this package here: https://github.com/FredKSchott/rollup-plugin-polyfill-node/commit/10ec9b4c9cf3d9323062cce9d7c7f756ab9aba28

I tried the earliest on npm, `0.3.0`, but the above release is already in there.

Comment (connorjclark) [reply node-modules-polyfill/src/index.ts:53]: also problematic is that some polyfill contents import `\0polyfill-node._stream_duplex`. Esbuild attempts to find this on disk but the polyfill package doesn't ship this anywhere, so there's no `resolveDir` we could set that would work.

Comment (connorjclark) [reply node-modules-polyfill/src/index.ts:53]: @FredKSchott should the imports here be inlined in your collect-polyfills script? https://github.com/FredKSchott/rollup-plugin-polyfill-node/blob/main/polyfills/stream.js#L4 

if not- what's the expected way to configure rollup/esbuild to handle these imports correctly?

Comment (connorjclark) [reply node-modules-polyfill/src/index.ts:53]: Sorry for quick & dirty gist delivery, but here is my now-working version of this patch: https://gist.github.com/connorjclark/5535d586af717e1d503cc71de31d840c

Comment (MichaelDeBoey) [reply node-modules-polyfill/src/index.ts:53]: @connorjclark Can you please add suggestions to this PR to what needs to change in order to make it work as you would expect to?

Comment (connorjclark) [reply node-modules-polyfill/src/index.ts:53]: Would it be better to just send a new PR? I'm not sure the original author is still around (and am not convinced it ever worked?)

Comment (connorjclark) [reply node-modules-polyfill/src/index.ts:53]: It's pretty much as described in my first two comments. I just checked out this PR as it is locally and ran the tests, and they all failed. Did this patch really work for you?

Comment (MichaelDeBoey) [reply node-modules-polyfill/src/index.ts:53]: I just updated the package according to the CHANGELOGs

Comment (MichaelDeBoey) [reply node-modules-polyfill/src/index.ts:53]: @connorjclark I just updated the package according to the CHANGELOGs in @FredKSchott's `rollup-plugin-polyfill-node`

Comment (MichaelDeBoey) [reply node-modules-polyfill/src/index.ts]: @connorjclark I updated the PR to account for the actual content instead of the path

**Comment by MichaelDeBoey** [comment]
@connorjclark @imranbarbhuiya I updated the PR to account for the actual content instead of the path
Could you please check if everything is working as expected now?

File: node-modules-polyfill/src/index.ts [hunk 2]
```diff
@@ -1,11 +1,9 @@
-import { OnResolveArgs, Plugin } from 'esbuild'
+import type { OnResolveArgs, Plugin } from 'esbuild'
+import esbuild from 'esbuild'
 import escapeStringRegexp from 'escape-string-regexp'
-import fs from 'fs'
 import path from 'path'
-import esbuild from 'esbuild'
-import { builtinsPolyfills } from './polyfills'
+import { getModules as builtinsPolyfills } from 'rollup-plugin-polyfill-node/dist/modules'
```
[the remark this answers is not in the document]
Comment (MichaelDeBoey) [reply node-modules-polyfill/src/index.ts:5]: I didn't want to update too much of the implementation-details & opted to update the unmaintained `rollup-plugin-node-polyfills` with @FredKSchott's fork (`rollup-plugin-polyfill-node`) instead as that has (about) the same API, so requires the least changes/work/deep-dive into the polyfill code.

We could move to another polyfill in a later PR if that's preferred.

[the remark this answers is not in the document]
Comment (giuseppeg) [reply node-modules-polyfill/src/index.ts:5]: Your call! Just keep in mind that Fred's plugin polyfills a whole bunch of things not just Node's `util` and therefore you will have a hard time if you want to replace it later

[the remark this answers is not in the document]
Comment (giuseppeg) [reply node-modules-polyfill/src/index.ts:5]: my initial issue was with util being outdated but if you think it is worth replacing the entire set of polyfill then probably rollup-plugin-polyfill-node is a good call. The owner of this repo might have more context/knowledge to give you the final thumbs up

[the remark this answers is not in the document]
Comment (MichaelDeBoey) [reply node-modules-polyfill/src/index.ts:5]: Does Fred's `util` work for you as well or is it missing some things?

[the remark this answers is not in the document]
Comment (MichaelDeBoey) [reply node-modules-polyfill/src/index.ts:5]: @giuseppeg It wasn't, but it should once https://github.com/FredKSchott/rollup-plugin-polyfill-node/pull/65 is merged I guess?

**Comment by ice1000** [comment]
💯💯💯💯 nice!!!

**Comment by MichaelDeBoey** [comment]
@remorses I think this one can be merged now
Anything else I need to do to get this one over the line?

**Comment by i7eo** [comment]
Is there progress?

**Comment by MichaelDeBoey** [comment]
@i7eo I'm a bit waiting for @remorses for this to get merged now, so we need to have some patience I'm afraid

File: node-modules-polyfill/src/index.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (MichaelDeBoey) [reply node-modules-polyfill/src/index.ts:5]: @giuseppeg https://github.com/FredKSchott/rollup-plugin-polyfill-node/pull/65 is now merged & released in `rollup-plugin-polyfill-node` v0.12.0, which is the version I use in this PR

**Comment by i7eo** [comment]
> @i7eo I'm a bit waiting for @remorses for this to get merged now, so we need to have some patience I'm afraid

alright, I got.

**Comment by ice1000** [comment]
Thanks very much!!!

**Comment by MichaelDeBoey** [comment]
@remorses It appears we have the same error @connorjclark was talking about in https://github.com/remorses/esbuild-plugins/pull/19#discussion_r990506227 in the Remix repo now that we updated to v0.2.0

> Cannot read directory "\x00polyfill-node._stream_duplex": invalid argument

Does any of you know a possible solution for that? 🙏
